# Configuration for News Aggregator Project

artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/Data_Ingestion
  input_path: "data/News_Aggregator_Kitwe_Data_Collection.csv"
  output_path: "artifacts/Data_Ingestion/News_Aggregator_Kitwe_Data_Collection.csv"

data_categorizer:
  root_dir: artifacts/Data_Categorizer
  input_path: "artifacts/Data_Ingestion/News_Aggregator_Kitwe_Data_Collection.csv"
  output_path: "artifacts/Data_Categorizer/News_Aggregator_labelled.csv"
  
  categories_keywords:
    sports: 
      - football
      - soccer
      - basketball
      - tennis
      - cricket
      - olympics
      - athlete
      - sports
    politics: 
      - government
      - election
      - politician
      - policy
      - parliament
      - minister
      - president
      - vote
    education: 
      - school
      - university
      - education
      - college
      - students
      - learning
      - teacher
      - scholarship
    health_and_wellness: 
      - health
      - hospital
      - doctor
      - wellness
      - mental health
      - fitness
      - medicine
      - disease
    development: 
      - development
      - infrastructure
      - construction
      - road
      - bridge
      - building
      - urbanization
    narcotics: 
      - narcotics
      - drug
      - cocaine
      - heroin
      - meth
      - drug trafficking
      - illegal drugs
    fashion: 
      - fashion
      - clothing
      - designer
      - runway
      - model
      - style
      - apparel
      - trends
    career: 
      - job
      - career
      - employment
      - opportunity
      - work
      - recruitment
      - hiring
      - position
    local_news: 
      - local
      - community
      - city
      - town
      - village
      - municipality
      - neighborhood
      - region
    economy_news: 
      - economy
      - economic
      - finance
      - market
      - stocks
      - currency
      - inflation
      - gdp
    business_news: 
      - business
      - company
      - corporation
      - entrepreneur
      - startup
      - industry
      - investment
      - profit

data_labelling:
  root_dir: artifacts/Data_Labelling
  input_path: "artifacts/Data_Categorizer/News_Aggregator_labelled.csv"
  output_path: "artifacts/Data_Labelling/final_data.csv"
  model_path: "artifacts/Data_Labelling/model.joblib"  

  reputable_sources:
    - bbc.com
    - reuters.com
    - nytimes.com
    - cnn.com
    - guardian.com
    - npr.org
    - forbes.com
    - bloomberg.com
    - washingtonpost.com
    - thetimes.co.uk
    - economist.com
    - wsj.com
    - cnbc.com
    - daily-mail.co.zm
    - times.co.zm
    - znbc.co.zm
    - flavaradioandtv.com
    - lusakatimes.com
    - kitwetimes.com

  suspicious_domain_patterns:
    - "\\.(info|lo|ru|cn|xyz|top|news|live|buzz|click|online)$"

  sensational_keywords:
    - shocking
    - unbelievable
    - amazing
    - incredible
    - secret
    - exposed
    - "you won't believe"
    - scandal
    - controversy

  thresholds:
    excessive_capitalization: 3
    sensational_keyword_count: 2
    sentiment_score: 0.5
    suspicious_links_count: 2

data_cleaning:
  root_dir: artifacts/Data_Cleaning
  input_path: "artifacts/Data_Labelling/final_data.csv"
  date_column: "Date"
  text_columns: ['Source', 'Category', 'Headline', 'Description']
  output_path: artifacts/Data_Cleaning/data/News_Aggregator_transformed.csv
